# Generated by Django 3.1.2 on 2020-10-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prompt', models.CharField(max_length=50)),
                ('decisive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AssisterFilterId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assisterId', models.IntegerField()),
                ('filterId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('imageFileName', models.CharField(max_length=50)),
                ('prosSummary', models.CharField(max_length=300)),
                ('consSummary', models.CharField(max_length=300)),
                ('assisterFilterIds', models.ManyToManyField(to='buyer.AssisterFilterId')),
                ('cons', models.ManyToManyField(to='buyer.Con')),
                ('pros', models.ManyToManyField(to='buyer.Pro')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('iconFileName', models.CharField(max_length=30)),
                ('assisters', models.ManyToManyField(to='buyer.Assister')),
                ('products', models.ManyToManyField(to='buyer.Product')),
            ],
        ),
        migrations.AddField(
            model_name='assister',
            name='filters',
            field=models.ManyToManyField(to='buyer.Filter'),
        ),
    ]
