# Generated by Django 3.1.2 on 2020-10-31 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assister',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='category',
            name='assisters',
        ),
        migrations.RemoveField(
            model_name='category',
            name='iconFileName',
        ),
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='assisterFilterIds',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pros',
        ),
        migrations.AddField(
            model_name='assister',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buyer.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assisterfilterid',
            name='product',
            field=models.ManyToManyField(to='buyer.Product'),
        ),
        migrations.AddField(
            model_name='con',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buyer.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='assister',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buyer.assister'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pro',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buyer.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='buyer.category'),
            preserve_default=False,
        ),
    ]
