# Generated by Django 3.1.2 on 2020-10-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20201031_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assisterfilterid',
            old_name='product',
            new_name='products',
        ),
    ]
