# Generated by Django 3.1.2 on 2020-10-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20201031_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products',
            new_name='assisterFilterIds',
        ),
    ]
