# Generated by Django 3.1.2 on 2020-11-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_auto_20201031_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consSummary',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='prosSummary',
            field=models.CharField(max_length=500),
        ),
    ]
