# Generated by Django 3.1.2 on 2020-11-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_auto_20201101_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternativeProducts',
            field=models.ManyToManyField(related_name='_product_alternativeProducts_+', to='buyer.Product'),
        ),
    ]
