# Generated by Django 3.1.2 on 2020-11-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_product_alternativeproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alternativeProducts',
        ),
        migrations.AddField(
            model_name='product',
            name='alternativeProductNames',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='batteryDescription',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='cameraDescription',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='displayDescription',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='entryCapacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='internalsDescription',
            field=models.CharField(default='', max_length=30),
        ),
    ]
