# Generated by Django 3.1.2 on 2020-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_auto_20201111_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ranking',
            field=models.IntegerField(default=100),
        ),
    ]
