# Generated by Django 3.1.2 on 2020-11-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_product_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alternativeProductNames',
        ),
    ]
