# Generated by Django 3.1.2 on 2020-11-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_remove_product_alternativeproductnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='internalsDescription',
        ),
    ]
