# Generated by Django 3.1.2 on 2020-11-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_remove_product_internalsdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='explanation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
