# Generated by Django 3.1.2 on 2020-11-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_filter_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assister',
            name='name',
        ),
    ]
