# Generated by Django 3.1.2 on 2020-11-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0014_remove_assister_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assister',
            name='advice',
            field=models.CharField(default='', max_length=500),
        ),
    ]
